### ISSUE TITLE
Install on Raspberry SO (bullseye) 

### ISSUE THREAD

**Issue by tripunto** [ned-kelly/docker-voltronic-homeassistant#99]
after many attempts I managed to get it to work correctly without unhealthy appearing on my 8gb raspberry pi 4b.

The solution was to uncomment the construction lines and add a command that delays the boot and waits for the mosquitto broker to start.

the added command is the following:

 ```
command: >
       /bin/bash -c "sleep 30; c -lk 0.0.0.0 1883;"
```

the complete docker-compose.yml file is as follows:

```
version: '3'

services:
  voltronic-mqtt:

    # We're now (finally) supporting Multi-Arch builds (via Github actions) on Docker Hub!
    image: bushrangers/ha-voltronic-mqtt

    # Uncomment if you want to build your own local version.
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: voltronic-mqtt

    privileged: true
    restart: always

    volumes:
        - ./config/:/etc/inverter/

    command: >
      /bin/bash -c "sleep 30; c -lk 0.0.0.0 1883;"
      
    devices:
    #  - "/dev/mem:/dev/mem"

    # USB Port Mapping
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
      - /dev/ttyUSB1:/dev/ttyUSB1:rwm

    # Serial Port Mapping...
      - /dev/ttyS0:/dev/ttyS0
      - /dev/ttyS1:/dev/ttyS1
      - /dev/ttyS2:/dev/ttyS2

  # Used to auto-update images as we release new versions...
  watchtower:
    # Please see the following for configuration options:
    #    https://containrrr.github.io/watchtower/container-selection/
    image: containrrr/watchtower
    container_name: watchtower

    restart: always
    privileged: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 500
```
